#!/bin/sh -e

##########################################################################
#   Synopsis:
#       
#   Description:
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2023-09-05  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 man-source [man-source ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi
files="$@"

in_name_section=no
for file in $files; do
    section=${file##*.}
    while read line; do
	if echo "$line" | grep -q '^\.SH.*NAME'; then
	    in_name_section=yes
	    # Debug: printf "Found NAME section.\n"
	elif [ $in_name_section = yes ]; then
	    # Quit at end of SYNOPSIS section
	    if echo "$line" | grep -q '^\.SH'; then
		in_name_section=no
		break   # Move on to next file
	    # Echo content of SYOPSIS section, but not tags
	    elif echo "$line" | grep -q '[\!-\~]' && \
		 ! echo "$line" | grep -q '^\.[A-Za-z]' && \
		 ! echo "$line" | grep -q '^\"'; then
		echo "$line" | sed -e "s|()|($section)|g"
	    fi
	fi
    done < $file
done
